#! /bin/bash

if [ "$#" -lt 2 ]; then
    echo "O programa $0 requer o nome do arquivo e arquivos que serão compactados"
    exit 1
fi

nome_arquivo="${1%.gz}_$(date +%Y%m%d%H).gz"  # Adiciona data e remove a extensão .gz se já existir
arquivos=("${@:2}") # Array que armazena todos os parâmetros a partir do segundo

# Verifica se o arquivo já está salvo, se tiver ele não salva novamente
if [ ! -e "$nome_arquivo" ]; then
    echo "Arquivo não encontrado: $nome_arquivo"
    echo "Compactando arquivos..."
    # Compacta os arquivos usando gzip
    gzip -c "${arquivos[@]}" > "$nome_arquivo"
    echo "Arquivos compactados em $nome_arquivo"
else
    echo "Arquivo já existente"
  fi
